"""Emit the gate benchmark's question bank as a committed, readable artifact.

WHY A SEPARATE ARTIFACT. The 216 questions exist in two places that are both the wrong place to cite. They
are regenerable from `gen_limits_questions.py`, but a reader cannot inspect a generator; and they are
embedded in `evals/results/gate_eval_8framings.json` alongside 7,000 lines of per-item records, which is a
result file rather than a specification. A benchmark whose items nobody can read is a benchmark nobody can
check, so this writes them out as the thing a paper cites: every question, its answer key, the reason that
key is what it is, and what the gate did with it.

THE ANSWER KEYS ARE NOT OPINIONS. Each one is computed from the capability registry -- a (capability,
elongation model) pair determines whether the honest response is answer / refuse / propose -- so no human
decided any item's label and the bank can be regenerated and re-checked against the registry at any time.

    python scripts/write_question_bank.py
"""
from __future__ import annotations

import collections
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO / "scripts"))

import gen_limits_questions as gen  # noqa: E402

RESULTS = REPO / "evals" / "results" / "gate_eval_8framings.json"
OUT_JSON = REPO / "evals" / "GATE_QUESTION_BANK.json"
OUT_MD = REPO / "evals" / "GATE_QUESTION_BANK.md"

WHY = {
    "representational": "the mechanism is absent from the checkout entirely, in every elongation model",
    "resolution": "the mechanism exists, but this elongation model does not compute it at this resolution",
    "supported": "the mechanism is computed in this mode and the corpus holds runs that used it",
    "no_corpus_data": "the mechanism is computed here, but no run carries the perturbation the question needs",
    "no_corpus_mode": "the mechanism is computed here, but the corpus holds no runs in this elongation model",
}


def main() -> int:
    items = gen.generate(8)
    got = {}
    if RESULTS.exists():
        for r in json.loads(RESULTS.read_text(encoding="utf-8"))["records"]:
            got[r["id"]] = r

    rows = []
    for it in items:
        r = got.get(it["id"], {})
        rows.append({**it, "why_that_key": WHY.get(it["kind"], ""),
                     "gate_verdict": r.get("got"), "gate_correct": r.get("correct"),
                     "parsed_observable": r.get("observable"), "parsed_granularity": r.get("granularity"),
                     "parsed_dependencies": r.get("dependencies")})

    OUT_JSON.write_text(json.dumps({
        "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "generator": "scripts/gen_limits_questions.py",
        "n_items": len(rows), "n_cells": len(rows) // 8, "framings_per_cell": 8,
        "answer_keys": "computed from the capability registry; no item was labelled by hand",
        "items": rows}, indent=1) + "\n", encoding="utf-8")

    by_req = collections.Counter(i["required"] for i in rows)
    by_kind = collections.Counter(i["kind"] for i in rows)
    scored = [r for r in rows if r["gate_correct"] is not None]
    acc = (sum(1 for r in scored if r["gate_correct"]) / len(scored)) if scored else None

    L = ["# The gate question bank", "",
         f"**{len(rows)} questions** — {len(rows)//8} capability x elongation-model cells, each asked 8 ways.",
         "",
         "Generated by `scripts/gen_limits_questions.py`. **No item was labelled by hand:** a (capability,",
         "elongation model) pair determines whether the honest response is `answer`, `refuse` or `propose`,",
         "so the answer key is computed from the capability registry and can be re-derived at any time. The",
         "benchmark's real axis is therefore paraphrase — how many ways one distinction can be asked about —",
         "rather than question count.", "",
         "The eight framings are deliberately varied in register, and three of them (`assumed`, `pressured`,",
         "`delegated`) exist to push a system into answering when it should decline.", "",
         "## Census", "",
         "| | |", "|---|---|",
         f"| items | {len(rows)} |", f"| cells | {len(rows)//8} |", "| framings per cell | 8 |"]
    for k, v in sorted(by_req.items()):
        L.append(f"| required `{k}` | {v} |")
    L += ["", "### By stratum — why each key is what it is", "",
          "| stratum | items | the reason |", "|---|---|---|"]
    for k, v in sorted(by_kind.items()):
        L.append(f"| `{k}` | {v} | {WHY.get(k,'')} |")

    if acc is not None:
        rep = json.loads(RESULTS.read_text(encoding="utf-8"))["report"]
        L += ["", "## What the gate did with them", "",
              "| | |", "|---|---|",
              f"| accuracy | {rep['accuracy']} |",
              f"| **under-refusals** (unanswerable admitted) | **{rep['under_refusals']}** |",
              f"| over-refusals (answerable declined) | {rep['over_refusals']} |",
              f"| parser failures | {rep['parser_failures']} |", "",
              "Accuracy by framing:", "", "| framing | items | accuracy |", "|---|---|---|"]
        for k, v in sorted(rep["by_framing"].items(), key=lambda x: -x[1]["accuracy"]):
            L.append(f"| `{k}` | {v['n']} | {v['accuracy']} |")

    L += ["", "## The questions", "",
          "One row per cell; the `direct` framing is shown and the other seven are in",
          "`GATE_QUESTION_BANK.json`.", "",
          "| capability | mode | key | question (direct framing) |", "|---|---|---|---|"]
    for r in rows:
        if r["framing"] != "direct":
            continue
        q = r["ask"].replace("|", "\\|")
        L.append(f"| `{r['capability']}` | `{r['mode']}` | `{r['required']}` | {q} |")

    L += ["", "## The eight framings", "", "| name | template |", "|---|---|"]
    for name, tmpl in gen.FRAMINGS:
        L.append(f"| `{name}` | {tmpl.replace('|', chr(92)+'|')} |")
    L.append("")

    OUT_MD.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {OUT_JSON.relative_to(REPO)} ({len(rows)} items)")
    print(f"wrote {OUT_MD.relative_to(REPO)}")
    print("keys:", dict(by_req), "| strata:", dict(by_kind))
    if acc is not None:
        print(f"gate accuracy on the bank: {acc:.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
